#!/bin/bash

# Check if a password was provided as an argument
if [ -z "$1" ]; then
    echo "Usage: $0 <password>"
    exit 1
fi

# Generate a MySQL dump
mysqldump -u root -p"$1" --all-databases > backup.sql

# Get the current date
date=$(date +%d-%m-%Y)

# Compress the MySQL dump
tar -czf "$date.tar.gz" backup.sql
