#!/bin/bash

# Install Nginx
apt-get update && apt-get install -y nginx

# Check if Nginx is listening on port 80
netstat -tulpn | grep 80

# If Nginx is not listening on port 80, start it
if ! [ -n "$(netstat -tulpn | grep 80)" ]; then
  service nginx start
fi

# Check again if Nginx is listening on port 80
netstat -tulpn | grep 80
